name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  pulumi-up:
    name: pulumi-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::445567079138:role/GitHubAction-AssumeRoleWithAction
          aws-region: us-west-2
          role-session-name: GitHubActionsSession

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./ppinfra
        run: npm install

      - name: Run Pulumi up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: rumanak/khanampulumi/rdev
          work-dir: ./ppinfra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_REGION: us-west-2  # Add this line
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
